Repository Inteli-College/2025-1A-T12-EC05-G01, pull requests merged in 2025-03, with the labels that each got.

#50 Feat/front sprint3
  src/software/frontend/package-lock.json
  src/software/frontend/package.json
  src/software/frontend/src/components/Chart.tsx
  src/software/frontend/src/pages/Dashboard.tsx
  src/software/frontend/src/pages/Estoque.tsx
  src/software/frontend/src/pages/Prescricoes.tsx
Labels: enhancement

#53 Feat: App-robo - pontos atualizados
  src/robo/app_dobot/functions/executar_rotina.py
  src/robo/pontos/pontos.json
Labels: enhancement

#54 Docs/esquematicos
  docs/docs/Sprint 3/Desenvolvimento/integracao_sistema.md
  docs/docs/Sprint 3/Esquemático/Esquematico.md
  docs/package-lock.json
  docs/package.json
  docs/sidebars.js
  docs/static/img/diagrama_sensores.png
  docs/static/img/esquematico_sensores.png
  docs/static/img/suporte_sensores.jpeg
Labels: documentation

#65 Fix/refatoracao
  src/database/database.db
  src/robo/LeitorQRCode/LeitorQRCode.py
  src/robo/SensorInfravermelho/SensorInfravermelho.py
  src/robo/app_dobot/app_dobot.py
  src/robo/app_dobot/functions/device_initializer.py
  src/robo/app_dobot/functions/executar_rotina.py
  src/robo/app_dobot/routes/__init__.py
  src/robo/app_dobot/routes/dobot.py
  src/robo/app_dobot/routes/fita.py
Labels: bug

#63 docs: adiciona documentação do banco de dados
  docs/docs/Sprint 4/Banco De Dados.md
  docs/sidebars.js
  docs/static/img/bancodedados.jpg
Labels: documentation

#76 :sparkles: feat: adiciona backend para adicionar bins
  src/robo/app_dobot/app_dobot.py
  src/robo/app_dobot/routes/bin.py
  src/robo/app_dobot/routes/dobot.py
  src/robo/pontos/carregar_medicamentos.py
  src/robo/pontos/fixos.py
  src/robo/pontos/pontos.json
Labels: enhancement

#95 docs: adiciona documentação do MQTT
  docs/docs/Sprint 4/MQTT/MQTT.md
  docs/sidebars.js
  docs/static/img/dobot_status.png
Labels: documentation
