Repository Inteli-College/2025-1A-T12-EC05-G01, pull requests merged in 2025-02, with the labels that each got.

#16 Fix/estrutura pastas
  README.md
  docs/docs/Arquitetura do Sistema/Requisitos/Funcionais.md
  docs/docs/Arquitetura do Sistema/Requisitos/Não Funcioanis.md
  docs/docs/Início.md
  docs/sidebars.js
  docs/src/pages/index.js
  docs/static/img/logo.png
Labels: documentation

#20 fix: corrige base url
  docs/docusaurus.config.js
Labels: bug

#27 Fix/Hotfixes-da-main
  docs/docs/Início.md
  docs/docusaurus.config.js
  docs/static/img/favicon.ico
  docs/static/img/logo.svg
Labels: bug

#25 Docs/user-stories
  .github/workflows/deploy.yaml
  docs/docs/Sprint 1/Arquitetura do Sistema/Diagrama de blocos.md
  docs/docs/Sprint 1/Arquitetura do Sistema/Requisitos/Funcionais.md
  docs/docs/Sprint 1/Arquitetura do Sistema/Requisitos/Não Funcioanis.md
  docs/docs/Sprint 1/Descrição da solução/Como a solução proposta deverá ser utilizada.md
  docs/docs/Sprint 1/Descrição da solução/Quais os benefícios trazidos pela solução proposta.md
  docs/docs/Sprint 1/Descrição da solução/Qual a solução proposta.md
  docs/docs/Sprint 1/Descrição da solução/Qual será o critério de sucesso e qual medida será utilizada para o avaliar.md
  docs/docs/Sprint 1/Descrição da solução/Qual é o problema a ser resolvido.md
  docs/docs/Sprint 1/Descrição da solução/_category_.json
  docs/docs/Sprint 1/Entendimento do Negócio/Matriz-e-nao-e.md
  docs/docs/Sprint 1/Entendimento do Negócio/canvas_da_proposta_de_valor.md
  docs/docs/Sprint 1/Entendimento do Negócio/canvas_mvp.md
  docs/docs/Sprint 1/Entendimento do Negócio/matriz_de_risco.md
  docs/docs/Sprint 1/Imersão preliminar/Pesquisa Desk/_category_.json
  docs/docs/Sprint 1/Imersão preliminar/Pesquisa Desk/encarte erros de medicação.md
  docs/docs/Sprint 1/Imersão preliminar/Pesquisa Desk/errosDeDispensaçãoNoAmbitoHospitalar.md
  docs/docs/Sprint 1/Imersão preliminar/Pesquisa Desk/estratégiasParaReduzirErros.md
  docs/docs/Sprint 1/Imersão preliminar/Pesquisa Desk/pesquisa desk.md
  docs/docs/Sprint 1/Imersão preliminar/definicao.md
  docs/docs/Sprint 1/Imersão preliminar/questionário.md
  docs/docs/Sprint 1/Imersão preliminar/tipos de pesquisa.md
  docs/docs/Sprint 1/Introdução do projeto/Introdução.md
  docs/docs/Sprint 1/Introdução do projeto/Justificativa.md
  docs/docs/Sprint 1/Introdução do projeto/Objetivos.md
  docs/docs/Sprint 1/Introdução do projeto/Proposta de solução.md
  docs/docs/Sprint 1/Introdução do projeto/_category_.json
  docs/docs/Sprint 1/Personas/Juliana/Juliana.md
  docs/docs/Sprint 1/Personas/Rodrigo.md
  docs/docs/Sprint 1/Personas/Rodrigo/Rodrigo.md
  docs/docs/Sprint 2/User Stories/user-stories.md
  docs/sidebars.js
Labels: documentation

#28 Feat/rotas
  src/software/app/templates/cadastro.html
  src/software/app/templates/dashboard.html
  src/software/app/templates/estoque.html
  src/software/app/templates/index.html
  src/software/app/templates/login.html
  src/software/app/templates/montagens.html
  src/software/app/templates/prescricoes.html
  src/software/app/templates/recuperarSenha.html
  src/software/app/templates/verificacao.html
  src/software/app/views.py
Labels: enhancement

#29 Docs/user flow
  docs/docs/Sprint 1/Entendimento do Negócio/canvas_da_proposta_de_valor.md
  docs/docs/Sprint 2/User Flow/user-flow.md
  docs/sidebars.js
  docs/static/img/cadastro-login-userflow.png
  docs/static/img/dashboard-sidebar.png
  docs/static/img/estoque-prescricoes.png
  docs/static/img/fitas-hardware.png
  docs/static/img/user-flow.png
Labels: documentation, ux

#30 Feat/front html
  src/software/app/static/images/logo.png
  src/software/app/templates/cadastro.html
  src/software/app/templates/dashboard.html
  src/software/app/templates/estoque.html
  src/software/app/templates/login.html
  src/software/app/templates/montagens.html
  src/software/app/templates/prescricoes.html
  src/software/app/templates/recuperarSenha.html
  src/software/app/templates/verificacao.html
Labels: enhancement

#36 Feat/CLI-final
  src/robo/CLI/CLI.py
  src/robo/CLI/clear_states.py
  src/robo/CLI/controle_manual.py
  src/robo/CLI/executar_rotina.py
  src/robo/CLI/help_cli.py
  src/robo/CLI/montar_fita.py
  src/robo/CLI/utils.py
  src/robo/pontos/pontos.json
Labels: enhancement
